version: '3.8'

services:
  api:
    image: node:18                # используем готовый образ Node.js
    working_dir: /app
    volumes:
      - .:/app                    # монтируем текущую папку внутрь контейнера
    command: npm run start:dev    # команда запуска твоего NestJS проекта
    ports:
      - '3003:3003'
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: cloak-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: